# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV4@4
  name: Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'Azure Resource Manager Service Connection'
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmStorageAccountName: 'sgaccountkhan10'
    backendAzureRmContainerName: 'sgaccountkhan10container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  name: Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformCLI@1
  inputs:
    command: 'forceunlock'
    allowTelemetryCollection: true
    lockID: 'dc42c916-a944-8d09-90e3-474978466f31'
- task: TerraformTaskV4@4
  name: Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    environmentServiceNameAzureRM: 'Azure Resource Manager Service Connection'


