# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@1
  name: Init
  inputs:
    command: 'init'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'Azure Resource Manager Service Connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'West Europe'
    backendAzureRmStorageAccountName: 'sgaccountkhan10'
    backendAzureRmContainerName: 'sgaccountkhan10container'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true

- task: TerraformTaskV4@4
  name: Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  name: Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    environmentServiceNameAzureRM: 'Azure Resource Manager Service Connection'

- task: TerraformTaskV4@4
  name: Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    environmentServiceNameAzureRM: 'Azure Resource Manager Service Connection'

# - task: TerraformTaskV4@4
#   name: Destroy
#   inputs:
#     provider: 'azurerm'
#     command: 'destroy'
#     commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
#     environmentServiceNameAzureRM: 'Azure Resource Manager Service Connection'



